drop database if exists smartkart;
create database smartkart;
use smartkart;

create table SK_PRODUCT(
PRODUCT_ID INT auto_increment,
NAME varchar(500) NOT NULL,
DESCRIPTION VARCHAR(1000) NOT NULL,
CATEGORY VARCHAR(250) NOT NULL,
BRAND VARCHAR(250) NOT NULL,
PRICE BIGINT NOT NULL,
QUANTITY SMALLINT NOT NULL,
constraint SK_PRODUCT_ID_PK primary key (PRODUCT_ID)
);

INSERT INTO SK_PRODUCT (PRODUCT_ID, NAME, DESCRIPTION, CATEGORY, BRAND, PRICE,QUANTITY) VALUES (1000,'Ps5','Play Station 5', 'gaming', 'playstation', 25000, 100);

create table SK_CUSTOMERSIGNIN(
	USER_EMAIL_ID varchar(500) NOT NULL UNIQUE KEY,
	USER_NAME varchar(500) NOT NULL,
	USER_PASSWORD varchar(500) NOT NULL,
    constraint SK_CUSTOMERSIGNIN_ID_PK primary key (USER_EMAIL_ID)
);